{
 "title": "LogoSeeker Grafana",
 "tags": [ "ultimate-enterprise" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Текущие показатели RPS и latency (спидометры)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"flask-backend\"}[1m]))"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Backend CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"logo_service\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[1m])) or vector(0)) / sum(rate(http_requests_total{}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Статистика времени ожидания отклика (FastAPI + YOLO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Статистика latency (P50, P90, P95, P99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))",
     "legendFormat": "P50 - Медианное время"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))",
     "legendFormat": "P90 - Перцентиль 90% запросов"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))",
     "legendFormat": "P95 - Перцентиль 95% запросов"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"flask-backend\"}[1m])) by (le))",
     "legendFormat": "P99 - Перцентиль 99% запросов"
    }
   ]
  },
  {
   "title": "Использование системных ресурсов (CPU и RAM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Container CPU Usage Profile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"logo_service\"}[1m])) * 100",
     "legendFormat": "Бэкенд (FastAPI)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"db\"}[1m])) * 100",
     "legendFormat": "База Данных (MariaDB)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"locust\"}[1m])) * 100",
     "legendFormat": "Тестер (Locust)"
    }
   ]
  },
  {
   "title": "Container RAM Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"logo_service\"} / 1024 / 1024",
     "legendFormat": "Бэкенд (FastAPI)"
    },
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"db\"} / 1024 / 1024",
     "legendFormat": "База Данных (MariaDB)"
    },
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"locust\"} / 1024 / 1024",
     "legendFormat": "Тестер (Locust)"
    }
   ]
  },
  { "title": "Аппаратная инфраструктура", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"logo_service\"}[1m]))",
     "legendFormat": "Входящая сеть (Rx)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"logo_service\"}[1m]))",
     "legendFormat": "Исходящая сеть (Tx)"
    }
   ]
  },
  {
   "title": "Physical Disk IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=\"logo_service\"}[1m]))",
     "legendFormat": "Скорость чтения диска"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container_label_com_docker_compose_service=\"logo_service\"}[1m]))",
     "legendFormat": "Скорость записи диска"
    }
   ]
  }
 ]
}