version: '3.8'

services:
  # БЭКЕНД (FastAPI)
  logo_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logo_seeker_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - logo_network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./models:/app/models:ro
      - ./bases:/app/bases:ro
      - ./classifier/config.py:/app/classifier/config.py:ro
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db:3306/avito_moderation"
      TORCH_FORCE_WEIGHTS_ONLY_LOAD: 0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # БАЗА ДАННЫХ
  db:
    image: mariadb:10.11
    container_name: logo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: avito_moderation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    networks:
      - logo_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ФРОНТЕНД (React + Nginx)
  frontend:
    build:
      context: ./logo-frontend
      dockerfile: Dockerfile
    container_name: logo_seeker_web
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - logo_network
    depends_on:
      - logo_service
  locust:
    image: locustio/locust:2.15.1
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
      - ./test_images:/mnt/locust/test_images:ro
    command: -f /mnt/locust/locustfile.py --host http://logo_service:8000
    networks:
      - logo_network
    restart: unless-stopped
    depends_on:
      - logo_service

  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules # Проброс правил для алертов
    networks:
      - logo_network
    restart: unless-stopped
    depends_on:
      - logo_service

  grafana:
    image: grafana/grafana:9.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - logo_network
    restart: unless-stopped
    depends_on:
      - prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: logo_seeker_cadvisor
    privileged: true
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /usr/lib/nvidia:/usr/lib/nvidia:ro
    networks:
      - logo_network
    restart: unless-stopped

networks:
  logo_network:
    driver: bridge

volumes:
  mysql_data: